# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-01 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170831_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_game',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
